# Generated by Django 3.2 on 2022-09-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_pic', '0003_rename_created_at_piclist_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='piclist',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='piclist',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
