# Generated by Django 3.2 on 2022-09-10 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_pic', '0005_alter_piclist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piclist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
