# Generated by Django 3.2 on 2022-09-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_pic', '0006_alter_piclist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piclist',
            name='birth_date',
            field=models.DateTimeField(verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='piclist',
            name='updated_at',
            field=models.DateTimeField(verbose_name='更新日時'),
        ),
    ]
