# Generated by Django 3.2 on 2022-09-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_pic', '0007_auto_20220910_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piclist',
            name='birth_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='piclist',
            name='end_period',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='piclist',
            name='start_period',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='piclist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
    ]
