# Generated by Django 3.2 on 2022-09-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_pic', '0008_auto_20220910_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piclist',
            name='end_period',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='piclist',
            name='start_period',
            field=models.DateTimeField(),
        ),
    ]
