# Generated by Django 3.2 on 2022-10-16 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_pic', '0010_auto_20221016_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piclist',
            name='first_name',
            field=models.CharField(blank=True, default=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='piclist',
            name='last_name',
            field=models.CharField(blank=True, default=False, max_length=50, null=True),
        ),
    ]
