# Generated by Django 3.2 on 2022-12-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_pic', '0015_auto_20221221_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
