# Generated by Django 3.2 on 2022-12-21 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_pic', '0018_auto_20221221_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piclist',
            name='family_name',
        ),
        migrations.RemoveField(
            model_name='piclist',
            name='first_name',
        ),
    ]
