# Generated by Django 3.2 on 2022-12-21 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_pic', '0019_auto_20221221_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piclist',
            name='end_period',
        ),
        migrations.RemoveField(
            model_name='piclist',
            name='start_period',
        ),
        migrations.AddField(
            model_name='piclist',
            name='season',
            field=models.CharField(blank=True, choices=[('danger', 'spring'), ('info', 'summer'), ('warning', 'Autumn'), ('light', 'winter'), ('dark', 'other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='piclist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_pic.myprofile'),
        ),
        migrations.AlterField(
            model_name='piclist',
            name='place',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
