# Generated by Django 3.2 on 2022-12-21 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_pic', '0020_auto_20221221_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='user_id',
            field=models.IntegerField(default=1, unique=True, verbose_name='ユーザ番号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='piclist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_pic.myprofile', to_field='user_id', verbose_name='投稿者'),
        ),
    ]
