# Generated by Django 3.2 on 2022-12-21 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_pic', '0021_auto_20221221_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piclist',
            name='user',
        ),
    ]
